version: '3.6'

services:
  book:
    environment:
      - CONFIG_SERVER_URI=config-server:8088
    expose:
      - 8080
    ports:
      - 8080:8080
    build:
      context: book
      dockerfile: book.dockerfile
    networks:
      - network1
  order:
    expose:
      - 8080
    ports:
      - 8085:8080
    build:
      context: order
      dockerfile: order.dockerfile
    networks:
      - network1
  delivery:
    expose:
      - 8080
    ports:
      - 8090:8080
    build:
      context: delivery
      dockerfile: delivery.dockerfile
    networks:
      - network1
  config-server:
    expose:
      - 9000
    ports:
      - 9000:8088
    build:
      context: config-server
      dockerfile: server.dockerfile
    networks:
      - network1
networks:
  network1:
    driver: bridge