spring:
  application:
    name: order-server
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: ${ZOOKEEPER_SERVER_URI:http://localhost:2181}
      max-retries: 5
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8888/eureka}
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true