spring:
  application:
    name: order-server
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8888/eureka}
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true